version: "3.2"

services:
  genetic-scheduler:
    build:
      context: .
    container_name: genetic_scheduler
    image: hoangph3/genetic-scheduler:1.0.0
    environment:
      - POPULATION_SIZE=300
      - NUMB_OF_ELITE_SCHEDULES=2
      - TOURNAMENT_SELECTION_SIZE=4
      - CROSSOVER_RATE=0.90
      - MUTATION_RATE=0.03
      - THREAD_TIMEOUT=1200
      - JOB_TIMEOUT=60
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
