version: "3.2"

services:
  mongodb:
    container_name: mongo_database
    image: mongo:6.0.1
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=P4ssW0rD
    volumes: 
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      # - ./mongo-data:/data/db
  
  mongo-express:
    container_name: mongo_express
    image: mongo-express:1.0.0-alpha
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=P4ssW0rD
    ports:
      - "8081:8081"

  genetic-scheduler:
    build: 
      context: .
    container_name: genetic_scheduler
    image: hoangph3/genetic-scheduler:1.0.0
    environment:
      - MONGO_USER=admin
      - MONGO_PASSWORD=P4ssW0rD
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
    depends_on:
      - mongodb
      - mongo-express
